version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - pollNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: mysqladmin ping -h localhost -u $DB_USERNAME -p$DB_PASSWORD
      interval: 60s
      timeout: 1s
      retries: 3
      start_period: 5s

  fluent-bit:
    image: fluent/fluent-bit:2.2.0
    container_name: fluent-bit
    networks:
      - pollNetwork
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/fluent-bit-parsers.conf:/fluent-bit/etc/fluent-bit-parsers.conf
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
    command: -c /fluent-bit/etc/fluent-bit.conf -log.level=debug

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    networks:
      - pollNetwork
    ports:
      - 3100:3100
      - 7946:7946
      - 9095:9095
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:10.2.1
    container_name: grafana
    networks:
      - pollNetwork
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3001:3000"
    volumes:
      - ./config/grafana.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    entrypoint:
      - sh
      - -euc
      - /run.sh
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    networks:
      - pollNetwork
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    networks:
      - pollNetwork
    ports:
      - 3200:3200
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    volumes:
      - ./config/tempo.yaml:/etc/tempo/config.yaml
    command: -config.file=/etc/tempo/config.yaml

networks:
  pollNetwork:
    name: pollNetwork
