version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - pollNetwork
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  fluent-bit:
    image: fluent/fluent-bit:2.2.0
    container_name: fluent-bit
    networks:
      - pollNetwork
    volumes:
      - ./config/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
    command: -c /fluent-bit/etc/fluent-bit.yaml

networks:
  pollNetwork:
    name: pollNetwork
