# https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

# https://opentelemetry.io/docs/collector/configuration/#exporters
exporters:
  otlphttp:
    endpoint: http://tempo:4318
  # prometheusremotewrite:
  #   endpoint: http://prometheus:9090/api/v1/push
  #   tls:
  #     insecure: true
  # debug:
  #   verbosity: detailed

# https://opentelemetry.io/docs/collector/configuration/#pipelines
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    # metrics:
    #   receivers: [otlp]
    #   exporters: [debug, prometheusremotewrite]
