global:
  scrape_interval: 15s

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
        - host.docker.internal:9090

  - job_name: poll-api
    static_configs:
      - targets:
        - poll:3000

  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090